### ISSUE TITLE
Checklist for release

### ISSUE THREAD

**Issue by jebyrnes** [Covid19R/covid19mobility#3]
- [x] Vignettes for goog and apple
- [x] Write tests
- [x] pkgdown site
- [x] Run all checks
- [x] Edit covid19R controlled vocab

**Comment by jebyrnes** [comment]
Submitted to CRAN!
